baseURL = "https://rusdy.com/"
title = "RA"
languageCode = "en-us"
theme = "PaperMod"

[pagination]
  pagerSize = 10

[params]
  env = "production"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  comments = false

  [params.profileMode]
    enabled = true
    title = "Rusdy Ahmad"
    subtitle = "Welcome to my blog"
    imageUrl = "https://github.com/rusdyahmad.png"
    imageTitle = "Profile Picture"

[[params.socialIcons]]
  name = "github"
  url  = "https://github.com/rusdyahmad"

[menu]
  [[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url  = "/posts/"
    weight = 2
